name: flutter_webview
description: 플러터 웹뷰
version: 1.0.0+1

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.0.0
  get: ^4.6.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  firebase_storage: ^11.2.3
  flutter_screenutil: ^5.8.4
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.1
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  package_info_plus: ^4.0.2
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  webview_flutter: ^4.4.2
  iamport_flutter: ^0.10.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  icons_launcher: ^2.1.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon.png"
      adaptive_background_color: '#782DFA'
      adaptive_foreground_image: "assets/icon.png"
      adaptive_round_image: "assets/icon.png"
      adaptive_monochrome_image: "assets/icon.png"
    ios: 
      enable: true

